source "https://rubygems.org"

gem 'activerecord', '~> 2.3.8'
gem 'activesupport', '~> 2.3.8'
gem 'bigdecimal', '~> 1.2.5'
gem 'dbi', '~> 0.4.5'
gem 'facets', '~> 2.9.3'
gem 'log4r', '~> 1.1.10'
gem 'serialport', '~> 1.3.0'

group :test do
  gem "rspec", "~> 2.14.1"
end
